name: "CI"
on:
  pull_request:
  push:
    # Comment out this section to enable testing of all branches.
    branches:
      - master
jobs:
  gnu-build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        emacs_version:
          - 26.3
          - 27.1
          - snapshot
    steps:
    - uses: purcell/setup-emacs@master
      with:
        version: ${{ matrix.emacs_version }}
    - uses: actions/setup-dotnet@v1
    - uses: actions/checkout@v2
    - uses: conao3/setup-cask@master
    - name: Install eldev
      run: curl -fsSL https://raw.github.com/doublep/eldev/master/webinstall/github-eldev | sh
    - name: Test
      run: |
        curl -O https://raw.githubusercontent.com/joaotavora/eglot/master/eglot-tests.el
        dotnet restore test/Test1
        eldev test
  windows-build:
    runs-on: windows-latest
    strategy:
      fail-fast: false
    steps:
    - uses: actions/setup-dotnet@v1
    - name: Install Cask/scoop-emacs
      run: |
        Set-ExecutionPolicy RemoteSigned -scope CurrentUser
        Invoke-Expression (New-Object System.Net.WebClient).DownloadString('https://get.scoop.sh')
        scoop update
        scoop bucket add extras
        scoop install emacs
        scoop install make
        echo "$env:PATH" | Out-File -Append -FilePath $env:GITHUB_PATH -Encoding utf8
    - uses: actions/checkout@v2
    - name: Install eldev
      run: iwr -useb https://raw.github.com/juergenhoetzel/eldev/powershell/webinstall/github-eldev.ps1 | iex
    - name: Eldev test
      run: |
        dotnet restore test/Test1
        eldev test



